apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlybooks-db-app
  labels:
    app: onlybooks-db-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onlybooks-db-app
  template:
    metadata:
      labels:
        app: onlybooks-db-app
    spec:
      volumes:
        - name: config-pv-volume
          persistentVolumeClaim:
            claimName: config-pv-claim
        - name: db-schema-volume
          configMap:
            name: db-schema-init
      containers:
      - name: onlybooks-db-image
        image: mariadb
        args: ["--lower_case_table_names=1"]
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: MARIADB_PASSWORD
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: MARIADB_ROOT_PASSWORD
        volumeMounts:
        - name: db-schema-volume
          mountPath: /docker-entrypoint-initdb.d/schema.sql
          subPath: schema.sql
        - name: config-pv-volume
          mountPath: "/var/lib/mysql"